Debug
adsabs/ADSScanExplorerService pull request #6
Opened 2024-01-04 18:10 UTC by femalves

2024-01-05 21:37 UTC, tjacovich reviewed
I think this looks good to start. I'm not sure we should merge it in currently, but we can build from this branch and test it out in dev next week.

2024-03-11 21:04 UTC, tjacovich approved these changes
Looks good. Fingers crossed it gives us something to chase down.

2024-04-08 19:15 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +                full_path = f'pdfs/{object_name}'
hitting full path with `'object_name'.lower()` might resolve the 404 issues. You'll just want to make sure that other places that use full path don't care if the case changes.

2024-07-17 15:42 UTC, femalves commented on config.py
> +AWS_BUCKET_NAME='<CHANGE ME>'
@tjacovich

2024-07-17 15:42 UTC, femalves commented on scan_explorer_service/utils/s3_utils.py
> +
@tjacovich

2024-07-17 15:42 UTC, femalves commented on scan_explorer_service/views/image_proxy.py
> +                response = Response(img2pdf.convert([im for im in loop_images(session, item, page_start, page_end, page_limit)]), mimetype='application/pdf')
@tjacovich

2024-07-17 15:42 UTC, femalves commented on scan_explorer_service/views/image_proxy.py
> +                current_app.logger.debug(line)
The profiling info will be removed before merging.

2024-07-25 18:49 UTC, tjacovich requested changes
Looks good. Just a couple of comments on logging and dependencies but then I think it should be good to go. We'll want to come up with a plan to have folks stress test the system and make sure that we have the pod resources scaled properly for production.

2024-07-25 18:49 UTC, tjacovich commented on dev-requirements.txt
> +boto3==1.34.75
You're good to just have this in the `requirements.txt`

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +import io, cProfile, pstats
You might be able to get rid of this line because I think you have removed the related profiling.

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +    current_app.logger.info(f'Request method: {request_method}')
Is this only logging if it is a `GET` request?

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +        current_app.logger.info(f'{e}')
I would maybe log this with the `.exception` logger so we also get a stack trace.

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +def fetch_images(session, item, page_start, page_end, page_limit, memory_limit):
I think a lot of the logs in here could be moved to `.debug` so that we have them but they aren't being logged by default. At least the `Id:` logs can probably dropped to `.debug`

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/views/image_proxy.py
> +        current_app.logger.info(f"Failed to get PDF using fallback method for {object_name}: {str(e)}")
I'd change this to be `.exception` as well

2024-07-25 18:49 UTC, tjacovich commented on scan_explorer_service/utils/s3_utils.py
> +            current_app.logger.info.exception(e)
I think this should just be `current_app.logger.exception`

2024-07-29 15:47 UTC, femalves commented on scan_explorer_service/views/image_proxy.py
> +    current_app.logger.info(f'Request method: {request_method}')
lol This was part of longer log I had added. For some reason I removed everything else, but forgot to remove this very important piece.

2024-08-22 18:56 UTC, tjacovich approved these changes

2024-09-12 15:22 UTC, merged